name: "Setup jq Example - Linux"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: "Version of jq to install"
        default: "1.6"
      download-compressed:
        type: boolean
        required: false
        description: "Download .tar.gz of binary rather than raw binary.  Save the tubes."
        default: true
      force:
        type: boolean
        required: false
        description: "Do not check for existing jq installation before continuing."
        default: false

jobs:
  example:
    runs-on: windows-latest
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v1.0.0
        with:
          version: '${{ inputs.version }}'
          download-compressed: '${{ inputs.download-compressed }}'
          force: '${{ inputs.force }}'

      - name: 'Check jq'
        run: |
          Get-Command "jq.exe"
          jq.exe --version
